# Generated by Django 2.1.4 on 2018-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181217_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default/profile-default.jpg', upload_to='accounts/%Y/%m/%d/', verbose_name='프로필 사진'),
        ),
    ]
