# Generated by Django 2.1.4 on 2018-12-17 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)])),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='스터디명')),
                ('photo', models.ImageField(default='default/group-default.jpg', upload_to='groups/%Y/%m/%d/', verbose_name='메인 이미지')),
                ('level', models.CharField(choices=[('초급', '초급'), ('중급', '중급'), ('고급', '고급')], default='elementary', max_length=30, verbose_name='레벨')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('day', models.CharField(choices=[('월요일', '월요일'), ('화요일', '화요일'), ('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일'), ('토요일', '토요일'), ('일요일', '일요일')], default='토요일', max_length=30, verbose_name='요일')),
                ('time', models.CharField(max_length=30, verbose_name='시간')),
                ('duration', models.PositiveSmallIntegerField(default=4, verbose_name='기간(주)')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='참여비(만원)')),
                ('size', models.PositiveSmallIntegerField(default=4, verbose_name='최대정원')),
                ('location', models.CharField(max_length=30, verbose_name='지역')),
                ('description', models.TextField(verbose_name='스터디 소개')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('full', 'Full')], default='active', max_length=40)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_of', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='member_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
