# Generated by Django 2.1.4 on 2018-12-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(verbose_name='스터디 소개'),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(max_length=30, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=140, verbose_name='스터디명'),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='default/group-default.jpg', upload_to='%Y/%m/%d/group/', verbose_name='메인 이미지'),
        ),
        migrations.AlterField(
            model_name='group',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='참여비(만원)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='최대정원'),
        ),
    ]
