# Generated by Django 2.1.4 on 2018-12-17 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20181217_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('full', 'Full')], default='active', max_length=40),
        ),
        migrations.AddField(
            model_name='group',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='default/group-default.jpg', upload_to='groups/%Y/%m/%d/', verbose_name='메인 이미지'),
        ),
    ]
